model:
    name: two_view_pipeline
    extractor:
      name: extractors.mast3r
    matcher:
      name: matchers.fast_nn
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 512
          edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      data:
        preprocessing:
          side: long
          resize: 512
          edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
