data:
    name: homographies
    data_dir: revisitop1m
    train_size: 150000
    val_size: 2000
    batch_size: 64
    num_workers: 14
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
    preprocessing:
        side: long
        resize: 512
        edge_divisible_by: 16
model:
    name: two_view_pipeline
    extractor:
        name: extractors.mast3r
        sparse_outputs: True
        dense_outputs: True
        coarse_descriptors: True
        max_num_keypoints: 512
        force_num_keypoints: True
        randomize_keypoints: True
        tiling_keypoints: False
        confidence_threshold: 0
        trainable: False
        head_type: mlp
        output_mode: desc24
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
        use_warp: True
        use_init_matching: True
        init_th_positive: 8.0
        init_th_negative: 8.0
    matcher:
        name: matchers.magicglue
        filter_threshold: 0.1
        loose_match_prob_threshold: 0.5
        flash: true
        mp: true
        checkpointed: true
        input_dim: 24
        input_coarse_dim: 1792
        n_blocks: 1
        n_layers: 3
        key_sample_mode: bilinear
train:
    seed: 0
    epochs: 40
    log_every_iter: 100
    eval_every_iter: 500
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      preprocessing:
        side: long
        resize: 512
        edge_divisible_by: 16
