data:
    name: homographies
    data_dir: revisitop1m
    train_size: 150000
    val_size: 2000
    batch_size: 128
    num_workers: 14
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
    preprocessing:
        side: long
        resize: 512
        edge_divisible_by: 16
model:
    name: two_view_pipeline
    extractor:
        name: extractors.mast3r
        sparse_outputs: True
        dense_outputs: False
        max_num_keypoints: 2048
        force_num_keypoints: True
        confidence_threshold: 0
        trainable: False
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        flash: false
        checkpointed: true
        input_dim: 24
train:
    seed: 0
    epochs: 40
    log_every_iter: 100
    eval_every_iter: 5000
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
