model:
    name: two_view_pipeline
    extractor:
        name: extractors.mast3r
        sparse_outputs: True
        dense_outputs: True
        coarse_descriptors: True
        max_num_keypoints: 512
        force_num_keypoints: True
        randomize_keypoints: True
        tiling_keypoints: False
        confidence_threshold: 0
        trainable: False
        head_type: mlp
        output_mode: desc24
    matcher:
        name: matchers.magicglue
        filter_threshold: 0.1
        flash: true
        mp: true
        checkpointed: true
        input_dim: 24
        input_coarse_dim: 1792
        n_blocks: 1
        n_layers: 3
        key_sample_mode: bilinear
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 512
          edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      data:
        preprocessing:
          side: long
          resize: 512
          edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
