model:
    name: two_view_pipeline
    extractor:
      name: extractors.roma
      max_num_matches: 5000
      coarse_res: [518, 518]
      upsample_preds: False
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
          # edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      data:
        preprocessing:
          side: long
          resize: 1600
          # edge_divisible_by: 16
      eval:
        estimator: opencv
        ransac_th: 0.5
